name: Scalafmt

permissions: {}

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Code is formatted
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check project is formatted
        uses: jrouly/scalafmt-native-action@v5
        with:
          arguments: '--list --mode diff-ref=origin/main'
