name: Link Validator

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  validate-links:
    runs-on: ubuntu-22.04
    if: github.repository == 'apache/pekko-connectors-kafka'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Java 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Install sbt
        uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8

      - name: Setup Coursier
        uses: coursier/setup-action@9b7939bf01fd1185ce2babe16135168361bf2c62 # v3.0.2

      - name: Build Documentation
        run: |-
          sbt docs/paradox unidoc
        env:
          JAVA_OPTS: "-verbose:gc -Xmx4g"

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.2.5 -- scripts/link-validator.conf
